# Generated by Django 6.1.1 on 2026-09-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLifestyleQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender_identity', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary_other', 'Non-binary / Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30)),
                ('current_situation', models.JSONField(blank=True, default=list)),
                ('meals_per_day', models.CharField(choices=[('1_or_fewer', '1 meal or fewer'), ('2', '2 meals'), ('3', '3 meals'), ('4_plus', '4+ meals')], max_length=20)),
                ('breakfast_days_per_week', models.CharField(choices=[('0', '0 days'), ('1_2', '1–2 days'), ('3_4', '3–4 days'), ('5_7', '5–7 days')], max_length=10)),
                ('meals_outside_home_frequency', models.CharField(choices=[('rarely_never', 'Rarely or never'), ('1_2', '1–2 times per week'), ('3_4', '3–4 times per week'), ('5_plus', '5 or more times per week')], max_length=20)),
                ('dietary_pattern', models.JSONField(blank=True, default=list)),
                ('dietary_pattern_other', models.CharField(blank=True, max_length=100)),
                ('freq_fruits_vegetables', models.CharField(choices=[('rarely_never', 'Rarely/Never'), ('1_2', '1–2 days/week'), ('3_4', '3–4 days/week'), ('5_7', '5–7 days/week')], max_length=20)),
                ('freq_whole_grains', models.CharField(choices=[('rarely_never', 'Rarely/Never'), ('1_2', '1–2 days/week'), ('3_4', '3–4 days/week'), ('5_7', '5–7 days/week')], max_length=20)),
                ('freq_lean_proteins', models.CharField(choices=[('rarely_never', 'Rarely/Never'), ('1_2', '1–2 days/week'), ('3_4', '3–4 days/week'), ('5_7', '5–7 days/week')], max_length=20)),
                ('freq_dairy_or_alternatives', models.CharField(choices=[('rarely_never', 'Rarely/Never'), ('1_2', '1–2 days/week'), ('3_4', '3–4 days/week'), ('5_7', '5–7 days/week')], max_length=20)),
                ('freq_processed_snacks', models.CharField(choices=[('rarely_never', 'Rarely/Never'), ('1_2', '1–2 days/week'), ('3_4', '3–4 days/week'), ('5_7', '5–7 days/week')], max_length=20)),
                ('water_cups_per_day', models.CharField(choices=[('less_than_3', 'Less than 3 cups'), ('3_5', '3–5 cups'), ('6_8', '6–8 cups'), ('more_than_8', 'More than 8 cups')], max_length=20)),
                ('sugar_sweetened_beverage_frequency', models.CharField(choices=[('rarely_never', 'Rarely or never'), ('1_3_week', '1–3 times per week'), ('4_6_week', '4–6 times per week'), ('1_plus_day', '1 or more times per day')], max_length=20)),
                ('caffeinated_beverages_per_day', models.CharField(choices=[('0', '0'), ('1_2', '1–2'), ('3_4', '3–4'), ('5_plus', '5 or more')], max_length=10)),
                ('physical_activity_days_per_week', models.CharField(choices=[('0', '0 days'), ('1_2', '1–2 days'), ('3_4', '3–4 days'), ('5_7', '5–7 days')], max_length=10)),
                ('screen_time_hours_per_day', models.CharField(choices=[('less_than_2', 'Less than 2 hours'), ('2_4', '2–4 hours'), ('5_7', '5–7 hours'), ('8_plus', '8 or more hours')], max_length=20)),
                ('sleep_hours_weekdays', models.CharField(choices=[('less_than_6', 'Less than 6 hours'), ('6_7', '6–7 hours'), ('8_9', '8–9 hours'), ('10_plus', '10 or more hours')], max_length=20)),
                ('supplements', models.JSONField(blank=True, default=list)),
                ('supplements_other', models.CharField(blank=True, max_length=100)),
                ('physical_symptoms', models.JSONField(blank=True, default=list)),
                ('skipped_meals_due_to_cost', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('confidence_access_healthy_meal', models.CharField(choices=[('highly_confident', 'Highly confident'), ('moderately_confident', 'Moderately confident'), ('not_confident', 'Not confident (lack of resources, time, or cooking skills)')], max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
